name: code-ezee

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
      - run: |
          npm config set strict-ssl false
          npm config set registry http://registry.npmjs.org

          npm install
          npm build
