name: code-ezee

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
      - run: |
          npm config set strict-ssl false
          npm config set registry http://registry.npmjs.org

          npm install
          npm run build
      - name: Upload dist folder
        uses: actions/upload-artifact@v1
        with:
          name: package
          path: dist
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download dist folder
      uses: actions/download-artifact@v1
      with:
        name: package
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: blitz-widget-store
        AWS_ACCESS_KEY_ID: 'AKIAJHPLKOEAIXY5MXPQ'
        AWS_SECRET_ACCESS_KEY: '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'
        AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'dist'
        DEST_DIR: 'packages'
    
